### ISSUE TITLE
Something wrong with Fig 4.(a).

### ISSUE THREAD

**Issue by eyuansu62** [Adaxry/Post-Instruction#1]
I think the attention scores in fig4(a) is inconsistency with the description "Focused attention on the source input". Maybe the bracket of "source input" is too short?

**Comment by Adaxry** [comment]
Thanks for your careful suggestion, the bracket of "source input" is indeed too short,  and we've fixed this issue in [Fig 4.(a)](https://github.com/Adaxry/Post-Instruction/blob/main/figures/heatmap_update.png).

**Comment by eyuansu62** [comment]
BTW, could u please share the plot code since the figures look nice.

**Comment by Adaxry** [comment]
Heatmap is plotted by this [example script](https://github.com/Adaxry/Post-Instruction/blob/main/scripts/plot_heatmap/plot_heatmap_attn.py), and the bracket and text are manually added via OmniGraffle.
